version: "3.9"

services:
  marvin_app:
    image: henriqueamitay/marvin-app
    hostname: marvin_app
    container_name: marvin_app
    ports:
      - target: 80
        published: 8080
        protocol: tcp
    networks:
      - marvin-network

  marvin_bot:
    image: henriqueamitay/marvin
    hostname: marvin
    container_name: marvin_bot
    init: true
    environment:
      "OUTPUT_PATH": "./playlist"
    volumes:
      - type: bind
        source: ./playlist
        target: /app/playlist
    ports:
      - target: 2000
        published: 2000
        protocol: tcp
    networks:
      - marvin-network

networks:
  marvin-network:
