version: "3.9"

services:
  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    container_name: rabbitmq
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
    networks:
      - marvin-network
  
  marvin_admin:
    image: henriqueamitay/marvin-admin
    hostname: marvin_admin
    container_name: marvin_admin
    restart: on-failure
    environment:
      "API_PORT": "5000"
      "QUEUE_HOST": "amqp://rabbitmq:5672"
      "DATABASE_URL": "file:./persistence/marvin.db"
      "OUTPUT_PATH": "/app/app/dist/playlist"
    volumes:
      - type: bind
        source: ./persistence
        target: /app/app/dist/prisma/persistence
      - type: bind
        source: ./playlist
        target: /app/app/dist/playlist
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    networks:
      - marvin-network
    depends_on:
      - "rabbitMq"

  marvin_app:
    image: henriqueamitay/marvin-app
    hostname: marvin_app
    container_name: marvin_app
    ports:
      - target: 80
        published: 8080
        protocol: tcp
    networks:
      - marvin-network

  marvin_bot:
    image: henriqueamitay/marvin
    hostname: marvin
    container_name: marvin_bot
    init: true
    environment:
      "OUTPUT_PATH": "./playlist"    
    volumes:
      - type: bind
        source: ./playlist
        target: /app/playlist
    ports:
      - target: 2000
        published: 2000
        protocol: tcp
    networks:
      - marvin-network
    
networks:
  marvin-network: