name: publish to docker hub
on:
  release:
    types: [published]

jobs:
  build-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          workdir: ./marvin-bot
          name: henriqueamitay/marvin
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          workdir: ./marvin-app
          name: henriqueamitay/marvin-app
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: [build-app, build-bot]
    runs-on: ubuntu-latest
    steps:
      - name: Run deployment script
        uses: fifsky/ssh-action@master
        with:
          command: |
            bash deploy.sh
          host: ${{ secrets.HOST }}
          user: root
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          args: "-tt -vvv"
