name: publish to docker hub
on:
  release:
    types: [published]

jobs:
  test-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Checkout code
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install dependencies and test
        working-directory: ./marvin-bot
        run: |
          npm install
          npm test

  test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Checkout code
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install dependencies and test
        working-directory: ./marvin-app
        run: |
          npm install
          export CI=true && npm run test

  build-bot:
    needs: [test-bot, test-app]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          workdir: ./marvin-bot
          name: henriqueamitay/marvin
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build-app:
    needs: [test-bot, test-app]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          workdir: ./marvin-app
          name: henriqueamitay/marvin-app
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: [build-app, build-bot]
    runs-on: ubuntu-latest
    steps:
      - name: Run deployment script
        uses: fifsky/ssh-action@master
        with:
          command: |
            bash deploy.sh
          host: ${{ secrets.HOST }}
          user: root
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          args: "-tt -vvv"
