name: publish to docker hub
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout code
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - run: cd marvin-bot
    - run: ls
    - run: npm install
    - run: npm test
